# Generated by Django 3.1.3 on 2021-09-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210806_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'Withdraw'), (3, 'Deposit')], default=3),
        ),
    ]
