# Generated by Django 3.1.3 on 2021-08-06 04:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, editable=False, max_length=150, null=True, unique=True)),
                ('email', models.EmailField(max_length=150)),
                ('mobile_no', models.CharField(max_length=10)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True)),
                ('establishment_year', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('post_office', models.CharField(blank=True, max_length=150, null=True)),
                ('police_station', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.CharField(max_length=150)),
                ('gst_no', models.CharField(blank=True, max_length=150, null=True)),
                ('privacy_policy', models.BooleanField(blank=True, default=False, null=True)),
                ('is_internet', models.BooleanField(blank=True, default=False, null=True)),
                ('is_inverter', models.BooleanField(blank=True, default=False, null=True)),
                ('is_drinking_water', models.BooleanField(blank=True, default=True, null=True)),
                ('computers', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six Or More')], default=0, null=True)),
                ('refrence_books', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six Or More')], default=0, null=True)),
                ('licensed_software', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six Or More')], default=0, null=True)),
                ('journal', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six Or More')], default=0, null=True)),
                ('cd', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six Or More')], default=0, null=True)),
                ('projector', models.IntegerField(blank=True, choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six Or More')], default=0, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('payment_reciept', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('order_id', models.CharField(blank=True, max_length=200, null=True)),
                ('signature', models.CharField(blank=True, max_length=200, null=True)),
                ('refrence_code', models.CharField(blank=True, max_length=200, null=True)),
                ('center_head_image', models.ImageField(max_length=150, upload_to='franchise/')),
                ('voter_id_card_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('pan_card_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('certificate_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('theory_room_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('practical_room_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('office_room_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('front_side_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('signature_image', models.ImageField(blank=True, max_length=150, null=True, upload_to='franchise/')),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('modified_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.district')),
            ],
            options={
                'verbose_name': 'Franchise',
                'verbose_name_plural': 'Franchises',
            },
        ),
        migrations.CreateModel(
            name='Refrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('modified_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refrence',
                'verbose_name_plural': 'Refrences',
            },
        ),
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('revert_message', models.TextField()),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('modified_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('franchise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Message Board',
                'verbose_name_plural': 'Message Boards',
            },
        ),
        migrations.CreateModel(
            name='InstituteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('modified_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institute Type',
                'verbose_name_plural': 'Institute Types',
            },
        ),
        migrations.CreateModel(
            name='Franchise_Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('points', models.IntegerField(default=0)),
                ('created_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('modified_on', models.DateField(default=datetime.datetime.now, editable=False)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duration', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='courses.duration')),
                ('franchise', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='franchises.franchise')),
            ],
            options={
                'verbose_name': 'Franchise Rank',
                'verbose_name_plural': 'Franchise Ranks',
            },
        ),
        migrations.AddField(
            model_name='franchise',
            name='institute_type',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='franchises.institutetype'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='payment_method',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.paymentmethod'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='plan',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.plan'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='refrence_from',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='franchises.refrence'),
        ),
        migrations.AddField(
            model_name='franchise',
            name='state',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='settings.state'),
        ),
    ]
